# Generated by Django 5.0.1 on 2024-01-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_alter_comment_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(blank=True, to="auctions.listing"),
        ),
        migrations.DeleteModel(
            name="Watchlist",
        ),
    ]
