# Generated by Django 5.0.1 on 2024-01-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_user_watchlist_delete_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("", "-----------------"),
                    ("General Merchandise", "General Merchandise"),
                    ("Electronics", "Electronics"),
                    ("Fashion", "Fashion"),
                    ("Home & Garden", "Home & Garden"),
                    ("Health & Beauty", "Health & Beauty"),
                    ("Toys & Hobbies", "Toys & Hobbies"),
                    ("Sports & Outdoors", "Sports & Outdoors"),
                    ("Media & Entertainment", "Media & Entertainment"),
                    ("Automotive", "Automotive"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                default=("", "-----------------"),
                max_length=64,
            ),
        ),
    ]
