# Generated by Django 5.0.1 on 2024-01-29 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_alter_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-----------------"),
                    ("GM", "General Merchandise"),
                    ("EL", "Electronics"),
                    ("FA", "Fashion"),
                    ("HG", "Home & Garden"),
                    ("HB", "Health & Beauty"),
                    ("TH", "Toys & Hobbies"),
                    ("SO", "Sports & Outdoors"),
                    ("ME", "Media & Entertainment"),
                    ("AU", "Automotive"),
                    ("MS", "Miscellaneous"),
                ],
                default=("", "-----------------"),
                max_length=64,
            ),
        ),
    ]
